/// ISO 3166-1 alpha-2 countries for proxy priority selection.
class ProxyCountry {
  const ProxyCountry(this.code, this.nameEn, this.nameFa);

  final String code;
  final String nameEn;
  final String nameFa;

  String present({required bool persian}) => '${persian ? nameFa : nameEn} ($code)';
}

/// Complete ISO 3166-1 alpha-2 list (UN M.49 / common VPN exits included).
abstract final class ProxyCountries {
  static const List<ProxyCountry> all = [
    ProxyCountry('AF', 'Afghanistan', 'افغانستان'),
    ProxyCountry('AL', 'Albania', 'آلبانی'),
    ProxyCountry('DZ', 'Algeria', 'الجزایر'),
    ProxyCountry('AS', 'American Samoa', 'ساموآی آمریکا'),
    ProxyCountry('AD', 'Andorra', 'آندورا'),
    ProxyCountry('AO', 'Angola', 'آنگولا'),
    ProxyCountry('AI', 'Anguilla', 'آنگویلا'),
    ProxyCountry('AQ', 'Antarctica', 'قطب جنوب'),
    ProxyCountry('AG', 'Antigua and Barbuda', 'آنتیگوا و باربودا'),
    ProxyCountry('AR', 'Argentina', 'آرژانتین'),
    ProxyCountry('AM', 'Armenia', 'ارمنستان'),
    ProxyCountry('AW', 'Aruba', 'آروبا'),
    ProxyCountry('AU', 'Australia', 'استرالیا'),
    ProxyCountry('AT', 'Austria', 'اتریش'),
    ProxyCountry('AZ', 'Azerbaijan', 'آذربایجان'),
    ProxyCountry('BS', 'Bahamas', 'باهاما'),
    ProxyCountry('BH', 'Bahrain', 'بحرین'),
    ProxyCountry('BD', 'Bangladesh', 'بنگلادش'),
    ProxyCountry('BB', 'Barbados', 'باربادوس'),
    ProxyCountry('BY', 'Belarus', 'بلاروس'),
    ProxyCountry('BE', 'Belgium', 'بلژیک'),
    ProxyCountry('BZ', 'Belize', 'بلیز'),
    ProxyCountry('BJ', 'Benin', 'بنین'),
    ProxyCountry('BM', 'Bermuda', 'برمودا'),
    ProxyCountry('BT', 'Bhutan', 'بوتان'),
    ProxyCountry('BO', 'Bolivia', 'بولیوی'),
    ProxyCountry('BA', 'Bosnia and Herzegovina', 'بوسنی و هرزگوین'),
    ProxyCountry('BW', 'Botswana', 'بوتسوانا'),
    ProxyCountry('BV', 'Bouvet Island', 'جزیره بووه'),
    ProxyCountry('BR', 'Brazil', 'برزیل'),
    ProxyCountry('IO', 'British Indian Ocean Territory', 'قلمرو اقیانوس هند بریتانیا'),
    ProxyCountry('BN', 'Brunei', 'برونئی'),
    ProxyCountry('BG', 'Bulgaria', 'بلغارستان'),
    ProxyCountry('BF', 'Burkina Faso', 'بورکینافاسو'),
    ProxyCountry('BI', 'Burundi', 'بوروندی'),
    ProxyCountry('CV', 'Cabo Verde', 'کیپ ورد'),
    ProxyCountry('KH', 'Cambodia', 'کامبوج'),
    ProxyCountry('CM', 'Cameroon', 'کامرون'),
    ProxyCountry('CA', 'Canada', 'کانادا'),
    ProxyCountry('KY', 'Cayman Islands', 'جزایر کیمن'),
    ProxyCountry('CF', 'Central African Republic', 'جمهوری آفریقای مرکزی'),
    ProxyCountry('TD', 'Chad', 'چاد'),
    ProxyCountry('CL', 'Chile', 'شیلی'),
    ProxyCountry('CN', 'China', 'چین'),
    ProxyCountry('CX', 'Christmas Island', 'جزیره کریسمس'),
    ProxyCountry('CC', 'Cocos (Keeling) Islands', 'جزایر کوکوس'),
    ProxyCountry('CO', 'Colombia', 'کلمبیا'),
    ProxyCountry('KM', 'Comoros', 'کومور'),
    ProxyCountry('CG', 'Congo', 'کنگو'),
    ProxyCountry('CD', 'Congo (DRC)', 'کنگو (دموکراتیک)'),
    ProxyCountry('CK', 'Cook Islands', 'جزایر کوک'),
    ProxyCountry('CR', 'Costa Rica', 'کاستاریکا'),
    ProxyCountry('CI', "Côte d'Ivoire", 'ساحل عاج'),
    ProxyCountry('HR', 'Croatia', 'کرواسی'),
    ProxyCountry('CU', 'Cuba', 'کوبا'),
    ProxyCountry('CW', 'Curaçao', 'کوراسائو'),
    ProxyCountry('CY', 'Cyprus', 'قبرس'),
    ProxyCountry('CZ', 'Czechia', 'جمهوری چک'),
    ProxyCountry('DK', 'Denmark', 'دانمارک'),
    ProxyCountry('DJ', 'Djibouti', 'جیبوتی'),
    ProxyCountry('DM', 'Dominica', 'دومینیکا'),
    ProxyCountry('DO', 'Dominican Republic', 'جمهوری دومینیکن'),
    ProxyCountry('EC', 'Ecuador', 'اکوادور'),
    ProxyCountry('EG', 'Egypt', 'مصر'),
    ProxyCountry('SV', 'El Salvador', 'السالوادور'),
    ProxyCountry('GQ', 'Equatorial Guinea', 'گینه استوایی'),
    ProxyCountry('ER', 'Eritrea', 'اریتره'),
    ProxyCountry('EE', 'Estonia', 'استونی'),
    ProxyCountry('SZ', 'Eswatini', 'اسواتینی'),
    ProxyCountry('ET', 'Ethiopia', 'اتیوپی'),
    ProxyCountry('FK', 'Falkland Islands', 'جزایر فالکلند'),
    ProxyCountry('FO', 'Faroe Islands', 'جزایر فارو'),
    ProxyCountry('FJ', 'Fiji', 'فیجی'),
    ProxyCountry('FI', 'Finland', 'فنلاند'),
    ProxyCountry('FR', 'France', 'فرانسه'),
    ProxyCountry('GF', 'French Guiana', 'گویان فرانسه'),
    ProxyCountry('PF', 'French Polynesia', 'پلی‌نزی فرانسه'),
    ProxyCountry('TF', 'French Southern Territories', 'سرزمین‌های جنوبی فرانسه'),
    ProxyCountry('GA', 'Gabon', 'گابن'),
    ProxyCountry('GM', 'Gambia', 'گامبیا'),
    ProxyCountry('GE', 'Georgia', 'گرجستان'),
    ProxyCountry('DE', 'Germany', 'آلمان'),
    ProxyCountry('GH', 'Ghana', 'غنا'),
    ProxyCountry('GI', 'Gibraltar', 'جبل‌الطارق'),
    ProxyCountry('GR', 'Greece', 'یونان'),
    ProxyCountry('GL', 'Greenland', 'گرینلند'),
    ProxyCountry('GD', 'Grenada', 'گرنادا'),
    ProxyCountry('GP', 'Guadeloupe', 'گوادلوپ'),
    ProxyCountry('GU', 'Guam', 'گوام'),
    ProxyCountry('GT', 'Guatemala', 'گواتمالا'),
    ProxyCountry('GG', 'Guernsey', 'گرنزی'),
    ProxyCountry('GN', 'Guinea', 'گینه'),
    ProxyCountry('GW', 'Guinea-Bissau', 'گینه بیسائو'),
    ProxyCountry('GY', 'Guyana', 'گویان'),
    ProxyCountry('HT', 'Haiti', 'هائیتی'),
    ProxyCountry('HM', 'Heard & McDonald Islands', 'جزایر هرد و مک‌دونالد'),
    ProxyCountry('VA', 'Vatican City', 'واتیکان'),
    ProxyCountry('HN', 'Honduras', 'هندوراس'),
    ProxyCountry('HK', 'Hong Kong', 'هنگ‌کنگ'),
    ProxyCountry('HU', 'Hungary', 'مجارستان'),
    ProxyCountry('IS', 'Iceland', 'ایسلند'),
    ProxyCountry('IN', 'India', 'هند'),
    ProxyCountry('ID', 'Indonesia', 'اندونزی'),
    ProxyCountry('IR', 'Iran', 'ایران'),
    ProxyCountry('IQ', 'Iraq', 'عراق'),
    ProxyCountry('IE', 'Ireland', 'ایرلند'),
    ProxyCountry('IM', 'Isle of Man', 'جزیره مان'),
    ProxyCountry('IL', 'Israel', 'اسرائیل'),
    ProxyCountry('IT', 'Italy', 'ایتالیا'),
    ProxyCountry('JM', 'Jamaica', 'جامائیکا'),
    ProxyCountry('JP', 'Japan', 'ژاپن'),
    ProxyCountry('JE', 'Jersey', 'جرزی'),
    ProxyCountry('JO', 'Jordan', 'اردن'),
    ProxyCountry('KZ', 'Kazakhstan', 'قزاقستان'),
    ProxyCountry('KE', 'Kenya', 'کنیا'),
    ProxyCountry('KI', 'Kiribati', 'کیریباتی'),
    ProxyCountry('KP', 'North Korea', 'کره شمالی'),
    ProxyCountry('KR', 'South Korea', 'کره جنوبی'),
    ProxyCountry('KW', 'Kuwait', 'کویت'),
    ProxyCountry('KG', 'Kyrgyzstan', 'قرقیزستان'),
    ProxyCountry('LA', 'Laos', 'لائوس'),
    ProxyCountry('LV', 'Latvia', 'لتونی'),
    ProxyCountry('LB', 'Lebanon', 'لبنان'),
    ProxyCountry('LS', 'Lesotho', 'لسوتو'),
    ProxyCountry('LR', 'Liberia', 'لیبریا'),
    ProxyCountry('LY', 'Libya', 'لیبی'),
    ProxyCountry('LI', 'Liechtenstein', 'لیختن‌اشتاین'),
    ProxyCountry('LT', 'Lithuania', 'لیتوانی'),
    ProxyCountry('LU', 'Luxembourg', 'لوکزامبورگ'),
    ProxyCountry('MO', 'Macao', 'ماکائو'),
    ProxyCountry('MG', 'Madagascar', 'ماداگاسکار'),
    ProxyCountry('MW', 'Malawi', 'مالاوی'),
    ProxyCountry('MY', 'Malaysia', 'مالزی'),
    ProxyCountry('MV', 'Maldives', 'مالدیو'),
    ProxyCountry('ML', 'Mali', 'مالی'),
    ProxyCountry('MT', 'Malta', 'مالت'),
    ProxyCountry('MH', 'Marshall Islands', 'جزایر مارشال'),
    ProxyCountry('MQ', 'Martinique', 'مارتینیک'),
    ProxyCountry('MR', 'Mauritania', 'موریتانی'),
    ProxyCountry('MU', 'Mauritius', 'موریس'),
    ProxyCountry('YT', 'Mayotte', 'مایوت'),
    ProxyCountry('MX', 'Mexico', 'مکزیک'),
    ProxyCountry('FM', 'Micronesia', 'میکرونزی'),
    ProxyCountry('MD', 'Moldova', 'مولداوی'),
    ProxyCountry('MC', 'Monaco', 'موناکو'),
    ProxyCountry('MN', 'Mongolia', 'مغولستان'),
    ProxyCountry('ME', 'Montenegro', 'مونته‌نگرو'),
    ProxyCountry('MS', 'Montserrat', 'مونتسرات'),
    ProxyCountry('MA', 'Morocco', 'مراکش'),
    ProxyCountry('MZ', 'Mozambique', 'موزامبیک'),
    ProxyCountry('MM', 'Myanmar', 'میانمار'),
    ProxyCountry('NA', 'Namibia', 'نامیبیا'),
    ProxyCountry('NR', 'Nauru', 'نائورو'),
    ProxyCountry('NP', 'Nepal', 'نپال'),
    ProxyCountry('NL', 'Netherlands', 'هلند'),
    ProxyCountry('NC', 'New Caledonia', 'کالدونیای جدید'),
    ProxyCountry('NZ', 'New Zealand', 'نیوزیلند'),
    ProxyCountry('NI', 'Nicaragua', 'نیکاراگوئه'),
    ProxyCountry('NE', 'Niger', 'نیجر'),
    ProxyCountry('NG', 'Nigeria', 'نیجریه'),
    ProxyCountry('NU', 'Niue', 'نیوئه'),
    ProxyCountry('NF', 'Norfolk Island', 'جزیره نورفولک'),
    ProxyCountry('MK', 'North Macedonia', 'مقدونیه شمالی'),
    ProxyCountry('MP', 'Northern Mariana Islands', 'جزایر ماریانای شمالی'),
    ProxyCountry('NO', 'Norway', 'نروژ'),
    ProxyCountry('OM', 'Oman', 'عمان'),
    ProxyCountry('PK', 'Pakistan', 'پاکستان'),
    ProxyCountry('PW', 'Palau', 'پالائو'),
    ProxyCountry('PS', 'Palestine', 'فلسطین'),
    ProxyCountry('PA', 'Panama', 'پاناما'),
    ProxyCountry('PG', 'Papua New Guinea', 'پاپوآ گینه نو'),
    ProxyCountry('PY', 'Paraguay', 'پاراگوئه'),
    ProxyCountry('PE', 'Peru', 'پرو'),
    ProxyCountry('PH', 'Philippines', 'فیلیپین'),
    ProxyCountry('PN', 'Pitcairn', 'پیتکرن'),
    ProxyCountry('PL', 'Poland', 'لهستان'),
    ProxyCountry('PT', 'Portugal', 'پرتغال'),
    ProxyCountry('PR', 'Puerto Rico', 'پورتوریکو'),
    ProxyCountry('QA', 'Qatar', 'قطر'),
    ProxyCountry('RE', 'Réunion', 'رئونیون'),
    ProxyCountry('RO', 'Romania', 'رومانی'),
    ProxyCountry('RU', 'Russia', 'روسیه'),
    ProxyCountry('RW', 'Rwanda', 'رواندا'),
    ProxyCountry('BL', 'Saint Barthélemy', 'سن بارتلمی'),
    ProxyCountry('SH', 'Saint Helena', 'سنت هلن'),
    ProxyCountry('KN', 'Saint Kitts and Nevis', 'سنت کیتس و نویس'),
    ProxyCountry('LC', 'Saint Lucia', 'سنت لوسیا'),
    ProxyCountry('MF', 'Saint Martin', 'سن مارتن'),
    ProxyCountry('PM', 'Saint Pierre and Miquelon', 'سن پیر و میکلون'),
    ProxyCountry('VC', 'Saint Vincent and the Grenadines', 'سنت وینسنت و گرنادین‌ها'),
    ProxyCountry('WS', 'Samoa', 'ساموآ'),
    ProxyCountry('SM', 'San Marino', 'سان مارینو'),
    ProxyCountry('ST', 'Sao Tome and Principe', 'سائوتومه و پرنسیپ'),
    ProxyCountry('SA', 'Saudi Arabia', 'عربستان سعودی'),
    ProxyCountry('SN', 'Senegal', 'سنگال'),
    ProxyCountry('RS', 'Serbia', 'صربستان'),
    ProxyCountry('SC', 'Seychelles', 'سیشل'),
    ProxyCountry('SL', 'Sierra Leone', 'سیرالئون'),
    ProxyCountry('SG', 'Singapore', 'سنگاپور'),
    ProxyCountry('SX', 'Sint Maarten', 'سنت مارتن'),
    ProxyCountry('SK', 'Slovakia', 'اسلواکی'),
    ProxyCountry('SI', 'Slovenia', 'اسلوونی'),
    ProxyCountry('SB', 'Solomon Islands', 'جزایر سلیمان'),
    ProxyCountry('SO', 'Somalia', 'سومالی'),
    ProxyCountry('ZA', 'South Africa', 'آفریقای جنوبی'),
    ProxyCountry('GS', 'South Georgia', 'جورجیا جنوبی'),
    ProxyCountry('SS', 'South Sudan', 'سودان جنوبی'),
    ProxyCountry('ES', 'Spain', 'اسپانیا'),
    ProxyCountry('LK', 'Sri Lanka', 'سری‌لانکا'),
    ProxyCountry('SD', 'Sudan', 'سودان'),
    ProxyCountry('SR', 'Suriname', 'سورینام'),
    ProxyCountry('SJ', 'Svalbard and Jan Mayen', 'سوالبارد و یان ماین'),
    ProxyCountry('SE', 'Sweden', 'سوئد'),
    ProxyCountry('CH', 'Switzerland', 'سوئیس'),
    ProxyCountry('SY', 'Syria', 'سوریه'),
    ProxyCountry('TW', 'Taiwan', 'تایوان'),
    ProxyCountry('TJ', 'Tajikistan', 'تاجیکستان'),
    ProxyCountry('TZ', 'Tanzania', 'تانزانیا'),
    ProxyCountry('TH', 'Thailand', 'تایلند'),
    ProxyCountry('TL', 'Timor-Leste', 'تیمور شرقی'),
    ProxyCountry('TG', 'Togo', 'توگو'),
    ProxyCountry('TK', 'Tokelau', 'توکلائو'),
    ProxyCountry('TO', 'Tonga', 'تونگا'),
    ProxyCountry('TT', 'Trinidad and Tobago', 'ترینیداد و توباگو'),
    ProxyCountry('TN', 'Tunisia', 'تونس'),
    ProxyCountry('TR', 'Türkiye', 'ترکیه'),
    ProxyCountry('TM', 'Turkmenistan', 'ترکمنستان'),
    ProxyCountry('TC', 'Turks and Caicos Islands', 'جزایر تورکس و کایکوس'),
    ProxyCountry('TV', 'Tuvalu', 'تووالو'),
    ProxyCountry('UG', 'Uganda', 'اوگاندا'),
    ProxyCountry('UA', 'Ukraine', 'اوکراین'),
    ProxyCountry('AE', 'United Arab Emirates', 'امارات متحده عربی'),
    ProxyCountry('GB', 'United Kingdom', 'بریتانیا'),
    ProxyCountry('US', 'United States', 'ایالات متحده آمریکا'),
    ProxyCountry('UM', 'U.S. Outlying Islands', 'جزایر دورافتاده آمریکا'),
    ProxyCountry('UY', 'Uruguay', 'اروگوئه'),
    ProxyCountry('UZ', 'Uzbekistan', 'ازبکستان'),
    ProxyCountry('VU', 'Vanuatu', 'وانواتو'),
    ProxyCountry('VE', 'Venezuela', 'ونزوئلا'),
    ProxyCountry('VN', 'Vietnam', 'ویتنام'),
    ProxyCountry('VG', 'British Virgin Islands', 'جزایر ویرجین بریتانیا'),
    ProxyCountry('VI', 'U.S. Virgin Islands', 'جزایر ویرجین آمریکا'),
    ProxyCountry('WF', 'Wallis and Futuna', 'والیس و فوتونا'),
    ProxyCountry('EH', 'Western Sahara', 'صحرای غربی'),
    ProxyCountry('YE', 'Yemen', 'یمن'),
    ProxyCountry('ZM', 'Zambia', 'زامبیا'),
    ProxyCountry('ZW', 'Zimbabwe', 'زیمبابوه'),
    ProxyCountry('AX', 'Åland Islands', 'جزایر آلاند'),
    ProxyCountry('BQ', 'Caribbean Netherlands', 'هلند کارائیب'),
    ProxyCountry('XK', 'Kosovo', 'کوزوو'),
  ];

  static final Map<String, ProxyCountry> _byCode = {
    for (final c in all) c.code: c,
  };

  static final Set<String> codes = {for (final c in all) c.code};

  /// Popular exits shown first in the picker; full list follows alphabetically.
  static const List<String> popularCodes = [
    'US',
    'DE',
    'TR',
    'GB',
    'NL',
    'FR',
    'JP',
    'SG',
    'CA',
    'AU',
    'IT',
    'ES',
    'SE',
    'CH',
    'FI',
    'NO',
    'PL',
    'AT',
    'BE',
    'BR',
    'IN',
    'KR',
    'HK',
    'TW',
    'AE',
    'RU',
    'IE',
    'PT',
    'RO',
    'CZ',
    'DK',
    'HU',
  ];

  static ProxyCountry? byCode(String code) => _byCode[code.toUpperCase()];

  static String present(String code, {required bool persian}) {
    final country = byCode(code);
    if (country == null) return code.toUpperCase();
    return country.present(persian: persian);
  }

  static List<ProxyCountry> sortedForPicker({required bool persian}) {
    final popular = <ProxyCountry>[];
    for (final code in popularCodes) {
      final c = byCode(code);
      if (c != null) popular.add(c);
    }
    final rest = all.where((c) => !popularCodes.contains(c.code)).toList()
      ..sort((a, b) => (persian ? a.nameFa : a.nameEn).compareTo(persian ? b.nameFa : b.nameEn));
    return [...popular, ...rest];
  }

  static List<ProxyCountry> search(String query, {required bool persian}) {
    final q = query.trim().toLowerCase();
    final source = sortedForPicker(persian: persian);
    if (q.isEmpty) return source;
    return source.where((c) {
      return c.code.toLowerCase().contains(q) ||
          c.nameEn.toLowerCase().contains(q) ||
          c.nameFa.contains(query.trim());
    }).toList();
  }
}
